### ISSUE TITLE
Not accepting servicetoken

### ISSUE THREAD

**Issue by ArijitU** [nogiszd/xiaomi-note-exporter#1] opened 2023-01-09 16:40 UTC
As many times I try it says - Provided session token was invalid or no longer active and couldn't access Mi Cloud.
I have even tried userId, guserid, mUserId

**Comment by ArijitU** [comment] 2023-01-09 18:25
Thank you for support. 
I am doing exactly as mentioned in readme and as you guided here. 

Check screenshots, same error

Latest chrome
![Screenshot 2023-01-09 234545](https://user-images.githubusercontent.com/3844967/211380129-f9832e26-d430-4566-bcea-75de71301015.png)

Choosing proper values by copying complete value

![Screenshot 2023-01-09 235119](https://user-images.githubusercontent.com/3844967/211380239-3af9a650-4a24-4741-8c94-b826e866c212.png)

Error screen

![Uploading Screenshot 2023-01-09 235205.png…]()

**Comment by nogiszd** [comment] 2023-01-09 19:48
@ArijitU 

Just released [new version](https://github.com/nogiszd/xiaomi-note-exporter/releases/latest) with different approach about determining whether user has signed in or not.

Please check if this resolved issue, personally I cannot reproduce this behaviour.

**Comment by ArijitU** [comment] 2023-01-09 23:29
Tried new release, sorry didn't work.
Have you hardcoded the URL in the software anywhere?
Asking because I noticed in developer tools, under cookies yours is https://us.i.mi.com/ and ours is https://i.mi.com/ so if your software is trying to go to us.i.mi.com that won't work here.

**Comment by ArijitU** [comment] 2023-01-09 23:37
I checked with Fiddler, indeed your app is trying to negotiate with us.i.mi.com, so that could be the issue

CONNECT us.i.mi.com:443 HTTP/1.1
**Host: us.i.mi.com:443**
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/108.0.5359.125 Safari/537.36

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

**Comment by nogiszd** [comment] 2023-01-10 06:58
@ArijitU 

Thank you for the reply.
Yes, I'm using **us.i.mi.com** domain as this is where Mi Cloud redirects me after signing in. 

After thinking I've come up with two root causes:

1. There may be region issue, based on region there are multiple domains for the same app (I'm in Europe, and based on your language code I reckon you are in India)
2. Domain may be based on used authentication method. I need info if you're using third party auth (eg. Facebook or Google)

Both will take me some time to consider and check if they are really responsible for that behaviour.

**Comment by ArijitU** [comment] 2023-01-10 08:21
1. Yes I am in India, a suggestion could be to pass URL as field value alongside session and userid
2. No I am not using third party authentication, plain simple MI email+password authentication

**Comment by nogiszd** [comment] 2023-01-10 08:39
Passing URL along with rest of the data could be a solution, but it will complicate whole process which is not suitable for end user.
When I decided to share this on GitHub I had simplicity on my mind, but as we see, it didn't work out.

At the same moment I will resolve issue whenever user is signing in with third party auth (check whether cookies are different or which are necessary to keep session alive).

**Comment by nogiszd** [comment] 2023-02-19 11:01
Hi @ArijitU, as I had some spare time I managed to create separate release for you to test.
It provides support for alternative support for multiple domains. [You can download it from here](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.0.8-pre).

I reckon cookies wouldn't be different between domains.

Let me know if this resolves this issue, and thank you for participate in tests!

**Comment by HansLau** [comment] 2023-03-17 13:14
Hi, it seems that I'm having the same issue, though not related to India, my domain is us.i.mi.com. I've tried using Firefox and Chrome to no avail.

**Comment by nogiszd** [comment] 2023-03-18 09:31
Hi, @HansLau, are you using the newest release, and the issue still persist?

**Comment by HansLau** [comment] 2023-03-18 11:57
Yes I've used 1.07 and the 1.08 pre release.

**Comment by nogiszd** [comment] 2023-03-18 19:15
So, even if you're using pre-release (with potential fix) you're still getting "servicetoken is invalid" error?

**Comment by HansLau** [comment] 2023-03-19 04:05
Yea. I don't think it's related to domain name, but I'm not sure what the issue is

**Comment by Crolug** [comment] 2023-10-25 17:27
Have the same issue.
Chrome: Version 118.0.5993.118 (Official Build) (64-bit)
App: 1.1.2
.NET: 6.0.24
Default domain of us.i.mi.com

**Comment by tabark92** [comment] 2023-10-29 14:58
I have the same issue also , Any help please ?

**Comment by nogiszd** [comment] 2023-10-29 16:26
@ArijitU @Crolug @HansLau @tabark92 

There is a [new release](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.2.0) that resolves this issue.

Mi Cloud have changed their auth system, so the issue became more apparent. 
Because it was regional issue back then I couldn't do much. I couldn't reproduce the behaviour.
Now it stopped working completely and I had to slightly modify the code.

Please let me know if this issue has been resolved with this update. Thanks.

**Comment by nogiszd** [comment] 2023-11-21 15:41
Closing as it seems to be resolved.

**Closed by nogiszd** 2023-11-21 15:41 UTC
Labels: bug, good first issue
